name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run typecheck

      - name: Run tests
        run: bun test

      - name: Build
        run: bun run build

      - name: Test MCP server starts
        run: |
          set +e  # Don't exit on error
          timeout 5s bun run dist/index.js
          exit_code=$?
          set -e  # Re-enable exit on error
          
          if [ "$exit_code" -eq 124 ]; then
            echo "✅ Server started successfully (timeout expected)"
            exit 0
          elif [ "$exit_code" -eq 0 ]; then
            echo "⚠️ Server exited unexpectedly with success"
            exit 1
          else
            echo "❌ Server failed to start with exit code: $exit_code"
            exit 1
          fi